export interface Project {
  id: number;
  title: string;
  slug: string;
  authorId: string;
  author: string;
  authorAvatar: string;
  description: string;
  image: string;
  category: string;
  categoryStyles: string;
  level: string;
  tags: string[];
  stars: number;
  views: number;
  comments: number;
  forks: number;
  createdAt: string;
  status: 'published' | 'draft';
}

export const projects: Project[] = [
  {
    id: 1,
    title: "ESP32 Radar Intrusion System",
    slug: "esp32-radar-intrusion",
    authorId: "user-2",
    author: "tech_wizard",
    authorAvatar: "https://i.pravatar.cc/150?u=user2",
    description: "A compact, low-power intrusion detection system using ESP32 and millimeter-wave radar sensors for precise motion tracking in industrial environments.",
    // PCB / soldering close-up
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80",
    category: "Electronics",
    categoryStyles: "bg-emerald-100/90 dark:bg-emerald-950/90 text-emerald-800 dark:text-emerald-300 border-emerald-200/50 dark:border-emerald-800/50 backdrop-blur-xl shadow-lg",
    level: "Advanced",
    tags: ["ESP32", "C++", "IoT", "Radar", "FreeRTOS"],
    stars: 1243,
    views: 4512,
    comments: 32,
    forks: 128,
    createdAt: "2026-01-15T09:00:00Z",
    status: "published",
  },
  {
    id: 2,
    title: "VLSI Cache Controller",
    slug: "vlsi-cache-controller",
    authorId: "user-3",
    author: "sarah_circuits",
    authorAvatar: "https://i.pravatar.cc/150?u=user3",
    description: "High-performance L2 cache controller design implemented in Verilog with LRU/LPLRU replacement policies, optimized for TSMC 28nm process.",
    // Silicon chip die close-up
    image: "https://images.unsplash.com/photo-1555664424-778a1e5e1b48?auto=format&fit=crop&w=900&q=80",
    category: "Hardware",
    categoryStyles: "bg-blue-100/90 dark:bg-blue-950/90 text-blue-800 dark:text-blue-300 border-blue-200/50 dark:border-blue-800/50 backdrop-blur-xl shadow-lg",
    level: "Expert",
    tags: ["Verilog", "FPGA", "VHDL", "VLSI", "SystemVerilog"],
    stars: 892,
    views: 2134,
    comments: 14,
    forks: 45,
    createdAt: "2026-01-20T11:30:00Z",
    status: "published",
  },
  {
    id: 3,
    title: "Autonomous Quadcopter Nav Stack",
    slug: "autonomous-quadcopter",
    authorId: "user-4",
    author: "drone_guy",
    authorAvatar: "https://i.pravatar.cc/150?u=user4",
    description: "Complete navigation stack for quadcopters featuring visual-inertial SLAM, dynamic obstacle avoidance, and multi-waypoint path planning using ROS2 Humble.",
    // Drone flying shot
    image: "https://images.unsplash.com/photo-1487887235947-a955ef187fcc?auto=format&fit=crop&w=900&q=80",
    category: "Robotics",
    categoryStyles: "bg-orange-100/90 dark:bg-orange-950/90 text-orange-800 dark:text-orange-300 border-orange-200/50 dark:border-orange-800/50 backdrop-blur-xl shadow-lg",
    level: "Intermediate",
    tags: ["ROS2", "Python", "OpenCV", "SLAM", "PX4"],
    stars: 543,
    views: 1873,
    comments: 21,
    forks: 89,
    createdAt: "2026-01-25T14:00:00Z",
    status: "published",
  },
  {
    id: 4,
    title: "Graph Neural Network Recommender",
    slug: "gnn-recommendations",
    authorId: "user-5",
    author: "ai_alex",
    authorAvatar: "https://i.pravatar.cc/150?u=user5",
    description: "Implementation of Graph Convolutional Networks for social network recommendation systems achieving 94.3% MAP@10 with PyTorch Geometric on OGB datasets.",
    // Neural network visualization / data science
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=900&q=80",
    category: "AI/ML",
    categoryStyles: "bg-violet-100/90 dark:bg-violet-950/90 text-violet-800 dark:text-violet-300 border-violet-200/50 dark:border-violet-800/50 backdrop-blur-xl shadow-lg",
    level: "Expert",
    tags: ["PyTorch", "GNN", "ML", "Python", "CUDA"],
    stars: 2108,
    views: 8934,
    comments: 56,
    forks: 312,
    createdAt: "2026-02-01T08:00:00Z",
    status: "published",
  },
  {
    id: 5,
    title: "Neural Engine Accelerator ASIC",
    slug: "neural-engine-asic",
    authorId: "user-2",
    author: "tech_wizard",
    authorAvatar: "https://i.pravatar.cc/150?u=user2",
    description: "Custom ASIC design for accelerating transformer-based neural networks with systolic array MAC units and on-chip SRAM. Taped out on GF 12nm.",
    // Semiconductor wafer / chip fab
    image: "https://images.unsplash.com/photo-1518481612222-68bbe828ebd1?auto=format&fit=crop&w=900&q=80",
    category: "Hardware",
    categoryStyles: "bg-blue-100/90 dark:bg-blue-950/90 text-blue-800 dark:text-blue-300 border-blue-200/50 dark:border-blue-800/50 backdrop-blur-xl shadow-lg",
    level: "Expert",
    tags: ["Verilog", "ASIC", "AI", "Synthesis", "DRC"],
    stars: 1521,
    views: 6201,
    comments: 42,
    forks: 156,
    createdAt: "2026-02-05T10:00:00Z",
    status: "published",
  },
  {
    id: 6,
    title: "LoRa Mesh Network",
    slug: "lora-mesh-network",
    authorId: "user-3",
    author: "sarah_circuits",
    authorAvatar: "https://i.pravatar.cc/150?u=user3",
    description: "Self-healing decentralized communication network for remote areas using LoRa SX1276 with optimized AODV routing. 30km range field-tested.",
    // Radio tower / antenna / RF waves
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=900&q=80",
    category: "Electronics",
    categoryStyles: "bg-emerald-100/90 dark:bg-emerald-950/90 text-emerald-800 dark:text-emerald-300 border-emerald-200/50 dark:border-emerald-800/50 backdrop-blur-xl shadow-lg",
    level: "Intermediate",
    tags: ["LoRa", "Arduino", "IoT", "Networking", "RF"],
    stars: 720,
    views: 3421,
    comments: 18,
    forks: 64,
    createdAt: "2026-02-08T12:00:00Z",
    status: "published",
  },
  {
    id: 7,
    title: "Real-Time OS Kernel for ARM",
    slug: "rtos-arm-kernel",
    authorId: "user-1",
    author: "bhavya_dev",
    authorAvatar: "https://i.pravatar.cc/150?u=user1",
    description: "A preemptive, priority-based RTOS kernel for ARM Cortex-M4 with cooperative round-robin scheduling, inter-task communication, and a custom heap allocator.",
    // ARM chip / microcontroller board
    image: "https://images.unsplash.com/photo-1501250987900-211872d97eaa?auto=format&fit=crop&w=900&q=80",
    category: "Software",
    categoryStyles: "bg-rose-100/90 dark:bg-rose-950/90 text-rose-800 dark:text-rose-300 border-rose-200/50 dark:border-rose-800/50 backdrop-blur-xl shadow-lg",
    level: "Expert",
    tags: ["C", "ARM", "RTOS", "Embedded", "Assembly"],
    stars: 634,
    views: 2890,
    comments: 11,
    forks: 78,
    createdAt: "2026-02-10T09:00:00Z",
    status: "published",
  },
  {
    id: 8,
    title: "Soft Robotic Gripper",
    slug: "soft-robotic-gripper",
    authorId: "user-4",
    author: "drone_guy",
    authorAvatar: "https://i.pravatar.cc/150?u=user4",
    description: "Pneumatically actuated soft gripper based on bellows-type actuators, handling fragile objects up to 500g without damage. 3D printed molds included.",
    // Robot arm / mechanical gripper
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=900&q=80",
    category: "Robotics",
    categoryStyles: "bg-orange-100/90 dark:bg-orange-950/90 text-orange-800 dark:text-orange-300 border-orange-200/50 dark:border-orange-800/50 backdrop-blur-xl shadow-lg",
    level: "Beginner",
    tags: ["3D Print", "Pneumatics", "ROS", "Python", "Actuator"],
    stars: 389,
    views: 1456,
    comments: 9,
    forks: 31,
    createdAt: "2026-02-12T15:00:00Z",
    status: "published",
  },
  {
    id: 9,
    title: "Diffusion Model from Scratch",
    slug: "diffusion-model-scratch",
    authorId: "user-5",
    author: "ai_alex",
    authorAvatar: "https://i.pravatar.cc/150?u=user5",
    description: "Clean, annotated implementation of DDPM and DDIM from first principles in pure PyTorch. Trains on CelebA-HQ in under 4 hours on a single A100.",
    // AI / machine learning visual
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=900&q=80",
    category: "AI/ML",
    categoryStyles: "bg-violet-100/90 dark:bg-violet-950/90 text-violet-800 dark:text-violet-300 border-violet-200/50 dark:border-violet-800/50 backdrop-blur-xl shadow-lg",
    level: "Expert",
    tags: ["PyTorch", "Diffusion", "Deep Learning", "CUDA", "Python"],
    stars: 3410,
    views: 14200,
    comments: 87,
    forks: 445,
    createdAt: "2026-02-15T07:00:00Z",
    status: "published",
  },
  {
    id: 10,
    title: "Open-Source Oscilloscope",
    slug: "open-source-oscilloscope",
    authorId: "user-1",
    author: "bhavya_dev",
    authorAvatar: "https://i.pravatar.cc/150?u=user1",
    description: "2-channel, 10MSPS oscilloscope built around STM32H7 and a 4-inch TFT. Supports USB data export, FFT mode, and a Python desktop companion app.",
    // Oscilloscope / test equipment / waveforms
    image: "https://images.unsplash.com/photo-1578022761797-b8636ac1773c?auto=format&fit=crop&w=900&q=80",
    category: "Electronics",
    categoryStyles: "bg-emerald-100/90 dark:bg-emerald-950/90 text-emerald-800 dark:text-emerald-300 border-emerald-200/50 dark:border-emerald-800/50 backdrop-blur-xl shadow-lg",
    level: "Advanced",
    tags: ["STM32", "C++", "DSP", "Embedded", "Python"],
    stars: 1788,
    views: 7341,
    comments: 63,
    forks: 201,
    createdAt: "2026-02-20T11:00:00Z",
    status: "published",
  },
];
